### PR TITLE
DAOS-623 lint: Change max line length to 100 chars

### PR DESCRIPTION
**Pull request by jolivier23**
Since Linux moved to 100 character line length, we should too

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
I tested this in my local copy and it works like a charm.

**Comment by ashleypittman** [comment]
Awesome.

I think this is a command line option so it may be possible to set it in pipeline-lib which would be slightly easier, plus we should modify the pylint rc file as well.

**Review by brianjmurrell — APPROVED** [review]
What about python code?  Are we enforcing any line length with the python linter(s)?

**Review by mchaarawi — APPROVED** [review]

**Comment by ashleypittman** [comment]
> What about python code? Are we enforcing any line length with the python linter(s)?

We only advise, not enforce line length but python is checked here:
https://github.com/daos-stack/daos/blob/master/utils/sl/pylint3.rc#L7

We should also update this to set "ColumnLimit: 100"
https://github.com/daos-stack/daos/blob/master/.clang-format

**Pull request merged**
