### PR TITLE
DAOS-7821 gha: Remove pylint from checks.

### PR DESCRIPTION
**Pull request by ashleypittman**
This should all be handled via github actions now, so remove
from Jenkins.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Sorry if this has been covered elsewhere so I may not have been pay close enough attention, but we also have this functionality covered in the githooks now, so that people still have an option to run it locally?

**Comment by ashleypittman** [comment]
> Sorry if this has been covered elsewhere so I may not have been pay close enough attention, but we also have this functionality covered in the githooks now, so that people still have an option to run it locally?

For pylint yes, a githook landed last week and you can run it directly at any time, below are example commands.  You can also use it as a plugin to Atom text editor to do annotations in-line, I'm working on making this compatible with VS Code as well but there's more work needed there yet.

```
./utils/cq/daos_pylint.py <file>
./utils/cq/daos_pylint.py --git
diff | ./utils/cq/daos_pylint.py --diff
```

Codespell is not in a githook yet but I've got code for that in https://github.com/daos-stack/daos/pull/8483 which I need to separate out and push.

**Review by jolivier23 — APPROVED** [review]

**Comment by ashleypittman** [comment]
Ok, I'm happier with this now, please review.

**Review by brianjmurrell — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]
LGTM. Once we get the GHA checks more stable, we'll probably want gatekeepers to require that patches don't introduce regressions

**Pull request merged**
